[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ltid_replication_package_lib"
version = "0.1.0"
authors = [{ name = "bolu61", email = "bolu61@zjc.dev" }]
dependencies = ["lxml", "pygit2"]
